# Generated by Django 5.0.3 on 2024-04-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0004_cartitem_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='shipping_method',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shipping_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
