# Generated by Django 5.0.3 on 2024-04-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0006_remove_cartitem_price_per_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
    ]
