# Generated by Django 5.0.3 on 2024-04-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_bookstore_price'),
        ('cartitems', '0007_remove_cartitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.bookstore'),
            preserve_default=False,
        ),
    ]
