# Generated by Django 5.0.3 on 2024-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0008_cartitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bookstore_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
