# Generated by Django 5.0.3 on 2024-04-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0010_alter_cartitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shipping_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
