# Generated by Django 5.0.3 on 2024-04-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0012_remove_cartitem_book_remove_cartitem_bookstore_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitembook',
            name='booktitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
