# Generated by Django 5.0.3 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitems', '0013_cartitembook_booktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='seller_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
