# Generated by Django 5.0.3 on 2024-03-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_bookstore_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='status',
        ),
    ]
