# Generated by Django 5.0.3 on 2024-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_bookstore_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
