# Generated by Django 5.0.3 on 2024-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_bookstore_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
