# Generated by Django 5.0.3 on 2024-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_bookstore_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='sold',
        ),
        migrations.AddField(
            model_name='bookstore',
            name='total_books',
            field=models.IntegerField(default=0),
        ),
    ]
