# Generated by Django 5.0.3 on 2024-03-29 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
