# Generated by Django 5.0.3 on 2024-03-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_created_at_cartitem_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_date',
        ),
    ]
